/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.UsuarioJpaController;
import Modelo.Usuario;
import Util.Crypto;
import Util.UserInterfaceSuport;
import Util.Validate;
import Util.Validate;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.net.ConnectException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.persistence.EntityManagerFactory;
import javax.persistence.NoResultException;
import javax.swing.InputVerifier;
import javax.swing.JOptionPane;

import javax.swing.GroupLayout;

/**
 *
 * @author Alfonso
 */
public class AutentificacionInicialVisual extends javax.swing.JDialog {

    public static Usuario usuarioAutentificado = null;
    private UsuarioJpaController usuarioJpaController = null;

    /**
     * Creates new form AutentificacionInicialVisual
     *
     * @param parent
     * @param modal
     * @param usuario
     */
    public AutentificacionInicialVisual() {
        this.setModal(true);
        this.usuarioJpaController = new UsuarioJpaController(javax.persistence.Persistence.createEntityManagerFactory("Prueba5PU"));
        //UserInterfaceSuport.centerComponent(this);
        //this.setLocationRelativeTo(null);
        initComponents();
        UserInterfaceSuport.centerComponent(this);
        autenjPanel4.setVisible(false);
        cambiarPanel2.setVisible(true);
        InputVerifier validadorPassword = Validate.validatePasswordEnvio(nuevoPasswordField2);
        nuevoPasswordField2.setInputVerifier(validadorPassword);
        InputVerifier validadorPassword1 = Validate.validatePasswordEnvio(passwordPasswordField);
        passwordPasswordField.setInputVerifier(validadorPassword1);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        cambiarPanel2 = new javax.swing.JPanel();
        contraseñaCheckBox1 = new javax.swing.JCheckBox();
        passwordPasswordField = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        usuarioTextField = new javax.swing.JTextField();
        cancelarButton = new javax.swing.JButton();
        aceptarButton = new javax.swing.JButton();
        autenjPanel4 = new javax.swing.JPanel();
        nuevoPasswordField2 = new javax.swing.JPasswordField();
        nuevoRepertirPasswordField = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        repetirLabel = new javax.swing.JLabel();
        cancelarCambiarButton = new javax.swing.JButton();
        aceptarCambiarContrasenaButton = new javax.swing.JButton();

        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel3.setLayout(new java.awt.CardLayout());

        contraseñaCheckBox1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        contraseñaCheckBox1.setText("Cambiar contraseña");
        contraseñaCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contraseñaCheckBox1ActionPerformed(evt);
            }
        });

        passwordPasswordField.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        passwordPasswordField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                passwordPasswordFieldKeyPressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel1.setText("Contraseña");

        jLabel2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel2.setText("Usuario");

        usuarioTextField.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        usuarioTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                usuarioTextFieldKeyPressed(evt);
            }
        });

        cancelarButton.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        cancelarButton.setText("Cancelar");
        cancelarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarButtonActionPerformed(evt);
            }
        });

        aceptarButton.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        aceptarButton.setText("Aceptar");
        aceptarButton.setName(""); // NOI18N
        aceptarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout cambiarPanel2Layout = new javax.swing.GroupLayout(cambiarPanel2);
        cambiarPanel2.setLayout(cambiarPanel2Layout);
        cambiarPanel2Layout.setHorizontalGroup(
            cambiarPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cambiarPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cambiarPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(contraseñaCheckBox1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cambiarPanel2Layout.createSequentialGroup()
                        .addGroup(cambiarPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(cambiarPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(47, 47, 47))
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(cambiarPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(cambiarPanel2Layout.createSequentialGroup()
                                .addComponent(aceptarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cancelarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(passwordPasswordField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 371, Short.MAX_VALUE)
                            .addComponent(usuarioTextField))))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        cambiarPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {aceptarButton, cancelarButton});

        cambiarPanel2Layout.setVerticalGroup(
            cambiarPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cambiarPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cambiarPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(usuarioTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(cambiarPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contraseñaCheckBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(cambiarPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cancelarButton, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                    .addComponent(aceptarButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        cambiarPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {aceptarButton, cancelarButton});

        jPanel3.add(cambiarPanel2, "card2");

        nuevoPasswordField2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        nuevoPasswordField2.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                nuevoPasswordField2CaretUpdate(evt);
            }
        });

        nuevoRepertirPasswordField.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        nuevoRepertirPasswordField.setEnabled(false);
        nuevoRepertirPasswordField.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                nuevoRepertirPasswordFieldCaretUpdate(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel3.setText("Nueva");

        repetirLabel.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        repetirLabel.setText("Repetir");

        cancelarCambiarButton.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        cancelarCambiarButton.setText("Cancelar");
        cancelarCambiarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarCambiarButtonActionPerformed(evt);
            }
        });

        aceptarCambiarContrasenaButton.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        aceptarCambiarContrasenaButton.setText("Aceptar");
        aceptarCambiarContrasenaButton.setName(""); // NOI18N
        aceptarCambiarContrasenaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarCambiarContrasenaButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout autenjPanel4Layout = new javax.swing.GroupLayout(autenjPanel4);
        autenjPanel4.setLayout(autenjPanel4Layout);
        autenjPanel4Layout.setHorizontalGroup(
            autenjPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(autenjPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(autenjPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(repetirLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(autenjPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(autenjPanel4Layout.createSequentialGroup()
                        .addComponent(cancelarCambiarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                        .addComponent(aceptarCambiarContrasenaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(nuevoPasswordField2)
                    .addComponent(nuevoRepertirPasswordField))
                .addContainerGap())
        );
        autenjPanel4Layout.setVerticalGroup(
            autenjPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(autenjPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(autenjPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nuevoPasswordField2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(autenjPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nuevoRepertirPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(repetirLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addGroup(autenjPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelarCambiarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(aceptarCambiarContrasenaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );

        autenjPanel4Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {aceptarCambiarContrasenaButton, cancelarCambiarButton});

        jPanel3.add(autenjPanel4, "card3");

        jPanel1.add(jPanel3, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    private void aceptarCambiarContrasenaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarCambiarContrasenaButtonActionPerformed
        if (!nuevoPasswordField2.getText().equalsIgnoreCase(nuevoRepertirPasswordField.getText())) {
            JOptionPane.showMessageDialog(AutentificacionInicialVisual.this, "La contraseña nueva no coincide");

        } else {
            usuarioAutentificado.setContraseña(Crypto.getEncryptedSHAString(nuevoPasswordField2.getText()));

            try {
                usuarioJpaController.edit(usuarioAutentificado);
                Principal.usuarioAutentificado = usuarioAutentificado;
                contraseñaCheckBox1.setSelected(false);

                nuevoRepertirPasswordField.setText("");
                nuevoPasswordField2.setText("");
                nuevoRepertirPasswordField.setEnabled(false);
                autenjPanel4.setVisible(false);
                cambiarPanel2.setVisible(true);
                JOptionPane.showMessageDialog(AutentificacionInicialVisual.this, "Exito al cambiar la contrasena");

            } catch (Exception ex) {
                JOptionPane.showMessageDialog(AutentificacionInicialVisual.this, "un error de exepcion");
            }

        }
        // TODO add your handling code here:
    }//GEN-LAST:event_aceptarCambiarContrasenaButtonActionPerformed

    private void cancelarCambiarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarCambiarButtonActionPerformed
        // TODO add your handling code here:

        nuevoRepertirPasswordField.setText("");
        nuevoPasswordField2.setText("");
        nuevoRepertirPasswordField.setEnabled(false);
        autenjPanel4.setVisible(false);
        cambiarPanel2.setVisible(true);

    }//GEN-LAST:event_cancelarCambiarButtonActionPerformed

    private void contraseñaCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contraseñaCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contraseñaCheckBox1ActionPerformed

    private void nuevoPasswordField2CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_nuevoPasswordField2CaretUpdate
        // TODO add your handling code here:
        if (!nuevoPasswordField2.getText().isEmpty()) {
            nuevoRepertirPasswordField.setEnabled(true);
        } else {
            nuevoRepertirPasswordField.setEnabled(false);
        }
    }//GEN-LAST:event_nuevoPasswordField2CaretUpdate

    private void nuevoRepertirPasswordFieldCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_nuevoRepertirPasswordFieldCaretUpdate
        // TODO add your handling code here:
        if (!nuevoRepertirPasswordField.getText().isEmpty()) {
            aceptarCambiarContrasenaButton.setEnabled(true);
        } else {
            aceptarCambiarContrasenaButton.setEnabled(false);
        }
    }//GEN-LAST:event_nuevoRepertirPasswordFieldCaretUpdate

    private void cancelarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarButtonActionPerformed
        // TODO add your handling code here:
        //dispose();
        usuarioAutentificado = null;
        this.closeDialog(null);
    }//GEN-LAST:event_cancelarButtonActionPerformed

    private void aceptarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarButtonActionPerformed
        // TODO add your handling code here:
        validateAll();
    }//GEN-LAST:event_aceptarButtonActionPerformed

    private void usuarioTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_usuarioTextFieldKeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (c == KeyEvent.VK_ENTER) {
//            passwordPasswordField.setCaretPosition(0);
            validateAll();
        }
    }//GEN-LAST:event_usuarioTextFieldKeyPressed

    private void passwordPasswordFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordPasswordFieldKeyPressed
        char c = evt.getKeyChar();
        if (c == KeyEvent.VK_ENTER) {
            validateAll();
//            if (usuarioTextField.getText().isEmpty() || passwordPasswordField.getPassword().length == 0) {
//                JOptionPane.showMessageDialog(AutentificacionInicialVisual.this, "Debe insertar usuario y contrasena");
//            } else {
//                try {
//                    usuarioAutentificado = usuarioJpaController.login(usuarioTextField.getText().toString(), Crypto.getEncryptedSHAString(String.valueOf(passwordPasswordField.getPassword())));
//                    if (usuarioAutentificado == null) {
//                        JOptionPane.showMessageDialog(AutentificacionInicialVisual.this, "usuario o contrasena incorrectos");
//                    } else {
//                        if (contraseñaCheckBox1.isSelected()) {
//                            autenjPanel4.setVisible(true);
//                            cambiarPanel2.setVisible(false);
//                        } else {
//                            dispose();
//                        }
//                    }
//
//                } catch (NullPointerException ex) {
//                    JOptionPane.showMessageDialog(AutentificacionInicialVisual.this, ex.getMessage(), "Usuario o contraseña inválidos", 2);
//                } catch (Exception ex) {
//                    Logger.getLogger(AutentificacionInicialVisual.class.getName()).log(Level.SEVERE, null, ex);
//                }
//            }
        }

    }//GEN-LAST:event_passwordPasswordFieldKeyPressed

    //Valida que todas los campos de usuario y contraseña esten correctos
    private void validateAll() {
        if (usuarioTextField.getText().isEmpty() || passwordPasswordField.getPassword().length == 0) {
            JOptionPane.showMessageDialog(AutentificacionInicialVisual.this, "Debe insertar usuario y contraseña");
        } else {
            if (String.valueOf(passwordPasswordField.getPassword()).length() < 5) {
                JOptionPane.showMessageDialog(AutentificacionInicialVisual.this, "El password debe poseer más de 5 caracteres");
            } else {

                try {
                    usuarioAutentificado = usuarioJpaController.login(usuarioTextField.getText(), Crypto.getEncryptedSHAString(String.valueOf(passwordPasswordField.getPassword())));

                    if (usuarioAutentificado == null) {

                    } else {
                        if (contraseñaCheckBox1.isSelected()) {
                            autenjPanel4.setVisible(true);
                            cambiarPanel2.setVisible(false);
                        } else {
                            dispose();
                            Principal.autenticado = true;
                            Principal.spprincipal.setVisible(true);
                            Principal.btnsalir.setVisible(true);
                            Principal.usuarioAutentificado = usuarioAutentificado;
                        }
                    }

                } catch (NoResultException ex) {
                    if (usuarioJpaController.findByName(usuarioTextField.getText()) != null) {
                        JOptionPane.showMessageDialog(AutentificacionInicialVisual.this, "Ya existe un usuario con este nombre");
                    } else {
                        int opcion = JOptionPane.showConfirmDialog(AutentificacionInicialVisual.this, "El usuario no se encuentra registrado. Desea registrarse");
                        if (opcion == 0) {
                            usuarioAutentificado = new Usuario();
                            usuarioAutentificado.setNombUsuario(usuarioTextField.getText());

                            System.out.println(passwordPasswordField.getPassword());

                            RegistroEstudiante registroEstudiante = new RegistroEstudiante(null, true, usuarioAutentificado);
                            registroEstudiante.setVisible(true);

                            dispose();
                        }

                        if (opcion == 1) {
                            passwordPasswordField.setText("");
                            usuarioTextField.setText("");
                        }
                    }
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(AutentificacionInicialVisual.this, "Usuario o contrasena invalido", "Usuario o contraseña inválidos", 2);
                }

            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AutentificacionInicialVisual dialog = new AutentificacionInicialVisual();
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptarButton;
    private javax.swing.JButton aceptarCambiarContrasenaButton;
    private javax.swing.JPanel autenjPanel4;
    private javax.swing.JPanel cambiarPanel2;
    private javax.swing.JButton cancelarButton;
    private javax.swing.JButton cancelarCambiarButton;
    private javax.swing.JCheckBox contraseñaCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPasswordField nuevoPasswordField2;
    private javax.swing.JPasswordField nuevoRepertirPasswordField;
    private javax.swing.JPasswordField passwordPasswordField;
    private javax.swing.JLabel repetirLabel;
    private javax.swing.JTextField usuarioTextField;
    // End of variables declaration//GEN-END:variables

}
