/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Vista;

import Util.UserInterfaceSuport;

import Controlador.ExperimentacionJpaController;
import Controlador.DimensionesRelevantesJpaController;
import Controlador.PosicionespuestotrabajoJpaController;
import Controlador.exceptions.IllegalOrphanException;
import Controlador.exceptions.NonexistentEntityException;

import Modelo.Experimentacion;
import Modelo.DimensionesRelevantes;
import Modelo.Posicionespuestotrabajo;
import java.awt.Component;
import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.util.LinkedList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.table.DefaultTableModel;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JList;
import javax.swing.JOptionPane;
import sun.awt.image.ByteArrayImageSource;
import sun.awt.image.ToolkitImage;

/**
 *
 * @author Eduardo
 */
public class casoestudio extends javax.swing.JDialog {

	/**
	 * Creates new form casoestudio
	 */
	private JFileChooser fc;
	private byte[] imgbyte;
	private Image foto;
	private InputStream is;
	private File file = null;
	private DefaultTableModel modeltabla;
	private DefaultListModel modellist1;
	private DefaultListModel modellist2;
	private DefaultListModel auxapasar1;
	private DefaultListModel auxapasar2;

	private Experimentacion modeloexp;
	private ExperimentacionJpaController controlexp;
	private DimensionesRelevantesJpaController controldimr;
	private PosicionespuestotrabajoJpaController controlposicPT;

	public casoestudio(java.awt.Frame parent, boolean modal) {
		super(parent, modal);
		initComponents();
		this.setModal(true);
		UserInterfaceSuport.centerComponent(this);

		controlexp = new ExperimentacionJpaController(
				javax.persistence.Persistence.createEntityManagerFactory("Prueba5PU"));
		controldimr = new DimensionesRelevantesJpaController(
				javax.persistence.Persistence.createEntityManagerFactory("Prueba5PU"));
		controlposicPT = new PosicionespuestotrabajoJpaController(
				javax.persistence.Persistence.createEntityManagerFactory("Prueba5PU"));

		// ********************funciones
		llenaTablaExperimentacio();
		llenaListaDR();
		llenaListaPP();
		auxapasar1 = new DefaultListModel();
		auxapasar2 = new DefaultListModel();

		btneliminar.setEnabled(false);
		btnmodificar.setEnabled(false);
		btndrA.setEnabled(false);
		btndrAt.setEnabled(false);
		btnposicA.setEnabled(false);
		btnposicAt.setEnabled(false);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		jPanel2 = new javax.swing.JPanel();
		jScrollPane2 = new javax.swing.JScrollPane();
		jScrollPane1 = new javax.swing.JScrollPane();
		tablacasoestudio = new javax.swing.JTable();
		jPanel4 = new javax.swing.JPanel();
		btninsertar = new javax.swing.JButton();
		btneliminar = new javax.swing.JButton();
		btnmodificar = new javax.swing.JButton();
		btnactualizar = new javax.swing.JButton();
		jLabel1 = new javax.swing.JLabel();
		txtnombre = new javax.swing.JTextField();
		jScrollPane3 = new javax.swing.JScrollPane();
		txtAdescripcion = new javax.swing.JTextArea();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		lblimagen = new javax.swing.JLabel();
		jLabel5 = new javax.swing.JLabel();
		jLabel6 = new javax.swing.JLabel();
		jLabel7 = new javax.swing.JLabel();
		jScrollPane4 = new javax.swing.JScrollPane();
		jlistdimr1 = new javax.swing.JList();
		btndrA = new javax.swing.JButton();
		jScrollPane5 = new javax.swing.JScrollPane();
		jlistdimr2 = new javax.swing.JList();
		jLabel8 = new javax.swing.JLabel();
		jLabel9 = new javax.swing.JLabel();
		jScrollPane6 = new javax.swing.JScrollPane();
		jlistposicion1 = new javax.swing.JList();
		jScrollPane7 = new javax.swing.JScrollPane();
		jlistposiciones2 = new javax.swing.JList();
		btnposicA = new javax.swing.JButton();
		btnposicAt = new javax.swing.JButton();
		btndrAt = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		setResizable(false);

		jPanel1.setLayout(new java.awt.CardLayout());

		jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

		tablacasoestudio.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
		tablacasoestudio.setModel(new javax.swing.table.DefaultTableModel(new Object[][] {

		}, new String[] { " Nombre de Caso de Estudio", " Descripción de Caso de Estudio" }) {
			boolean[] canEdit = new boolean[] { false, false };

			public boolean isCellEditable(int rowIndex, int columnIndex) {
				return canEdit[columnIndex];
			}
		});
		tablacasoestudio.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				tablacasoestudioMouseClicked(evt);
			}
		});
		jScrollPane1.setViewportView(tablacasoestudio);

		jScrollPane2.setViewportView(jScrollPane1);

		jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 11, 751, 199));

		jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

		btninsertar.setText("Insertar");
		btninsertar.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btninsertarActionPerformed(evt);
			}
		});

		btneliminar.setText("Eliminar");
		btneliminar.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btneliminarActionPerformed(evt);
			}
		});

		btnmodificar.setText("Modificar");
		btnmodificar.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnmodificarActionPerformed(evt);
			}
		});

		btnactualizar.setText("Actualizar");
		btnactualizar.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnactualizarActionPerformed(evt);
			}
		});

		jLabel1.setText("Nombre:");

		txtAdescripcion.setColumns(20);
		txtAdescripcion.setLineWrap(true);
		txtAdescripcion.setRows(5);
		txtAdescripcion.setWrapStyleWord(true);
		jScrollPane3.setViewportView(txtAdescripcion);

		jLabel2.setText("Descripción:");

		jLabel3.setText("Imagen");

		lblimagen.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, null,
				new java.awt.Color(0, 0, 0)));
		lblimagen.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
		lblimagen.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				lblimagenMouseClicked(evt);
			}
		});

		jLabel5.setText("Dimensiones");

		jLabel6.setText("relevantes");

		jLabel7.setText(" del diseño");

		jlistdimr1.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				jlistdimr1MouseClicked(evt);
			}
		});
		jlistdimr1.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
			public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
				jlistdimr1ValueChanged(evt);
			}
		});
		jScrollPane4.setViewportView(jlistdimr1);

		btndrA.setText(">>");
		btndrA.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btndrAActionPerformed(evt);
			}
		});

		jlistdimr2.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				jlistdimr2MouseClicked(evt);
			}
		});
		jlistdimr2.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
			public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
				jlistdimr2ValueChanged(evt);
			}
		});
		jScrollPane5.setViewportView(jlistdimr2);

		jLabel8.setText("Posiciones del puesto");

		jLabel9.setText("de trabajo");

		jlistposicion1.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				jlistposicion1MouseClicked(evt);
			}
		});
		jlistposicion1.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
			public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
				jlistposicion1ValueChanged(evt);
			}
		});
		jScrollPane6.setViewportView(jlistposicion1);

		jlistposiciones2.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				jlistposiciones2MouseClicked(evt);
			}
		});
		jlistposiciones2.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
			public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
				jlistposiciones2ValueChanged(evt);
			}
		});
		jScrollPane7.setViewportView(jlistposiciones2);

		btnposicA.setText(">>");
		btnposicA.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnposicAActionPerformed(evt);
			}
		});

		btnposicAt.setText("<<");
		btnposicAt.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnposicAtActionPerformed(evt);
			}
		});

		btndrAt.setText("<<");
		btndrAt.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btndrAtActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
		jPanel4.setLayout(jPanel4Layout);
		jPanel4Layout
				.setHorizontalGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(jPanel4Layout.createSequentialGroup().addGroup(jPanel4Layout
								.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(
										javax.swing.GroupLayout.Alignment.TRAILING,
										jPanel4Layout
												.createSequentialGroup().addGap(0, 0, Short.MAX_VALUE)
												.addComponent(btninsertar).addGap(9, 9,
														9)
												.addComponent(btneliminar).addGap(11, 11, 11).addComponent(btnmodificar)
												.addGap(15, 15, 15).addComponent(btnactualizar))
								.addGroup(jPanel4Layout.createSequentialGroup().addGap(31, 31, 31)
										.addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 73,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(18, 18, 18)
										.addComponent(lblimagen, javax.swing.GroupLayout.PREFERRED_SIZE, 135,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(21, 21, 21)
										.addGroup(jPanel4Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 150,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 120,
														javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 0,
												Short.MAX_VALUE)
										.addGap(18, 18, 18)
										.addGroup(jPanel4Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(btnposicA, javax.swing.GroupLayout.PREFERRED_SIZE, 67,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(btnposicAt, javax.swing.GroupLayout.PREFERRED_SIZE, 67,
														javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 105,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGroup(jPanel4Layout
										.createSequentialGroup().addGap(31, 31, 31)
										.addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 73,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(18, 18, 18).addComponent(txtnombre))
								.addGroup(
										jPanel4Layout.createSequentialGroup().addGap(30, 30, 30)
												.addGroup(jPanel4Layout
														.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE,
																90, javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE,
																90, javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE,
																80, javax.swing.GroupLayout.PREFERRED_SIZE))
												.addGap(2, 2, 2)
												.addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 276,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
												.addGroup(jPanel4Layout
														.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(btndrA).addComponent(btndrAt))
												.addGap(18, 18, 18).addComponent(jScrollPane5))
								.addGroup(jPanel4Layout.createSequentialGroup().addGap(31, 31, 31)
										.addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 73,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(18, 18, 18).addComponent(jScrollPane3)))
								.addContainerGap()));
		jPanel4Layout.setVerticalGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel4Layout.createSequentialGroup().addGap(32, 32, 32)
						.addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(
										jPanel4Layout.createSequentialGroup().addGap(11, 11, 11).addComponent(jLabel1))
								.addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 28,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(18, 18, 18)
						.addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(
										jPanel4Layout.createSequentialGroup().addGap(44, 44, 44).addComponent(jLabel2))
								.addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 112,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(jPanel4Layout.createSequentialGroup().addGroup(jPanel4Layout
										.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addGroup(jPanel4Layout.createSequentialGroup().addGap(18, 18, 18)
												.addGroup(jPanel4Layout
														.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(lblimagen, javax.swing.GroupLayout.PREFERRED_SIZE,
																113, javax.swing.GroupLayout.PREFERRED_SIZE)
														.addGroup(jPanel4Layout.createSequentialGroup()
																.addGap(50, 50, 50).addComponent(jLabel8)
																.addGap(6, 6, 6).addComponent(jLabel9))
														.addGroup(jPanel4Layout.createSequentialGroup()
																.addGap(18, 18, 18).addComponent(jScrollPane7,
																		javax.swing.GroupLayout.PREFERRED_SIZE, 96,
																		javax.swing.GroupLayout.PREFERRED_SIZE))))
										.addGroup(jPanel4Layout.createSequentialGroup().addGap(36, 36, 36).addComponent(
												jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 92,
												javax.swing.GroupLayout.PREFERRED_SIZE)))
										.addGap(17, 17, 17))
								.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
										jPanel4Layout.createSequentialGroup()
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addGroup(jPanel4Layout
														.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
																jPanel4Layout.createSequentialGroup()
																		.addComponent(btnposicA).addGap(18, 18, 18)
																		.addComponent(btnposicAt).addGap(33, 33, 33))
														.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
																jPanel4Layout.createSequentialGroup()
																		.addComponent(jLabel3).addGap(62, 62, 62)))))
						.addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(jPanel4Layout.createSequentialGroup().addGap(30, 30, 30).addComponent(jLabel5)
										.addGap(6, 6, 6).addComponent(jLabel6).addGap(6, 6, 6).addComponent(jLabel7))
								.addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 120,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 120,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGroup(jPanel4Layout.createSequentialGroup().addGap(33, 33, 33).addComponent(btndrA)
										.addGap(18, 18, 18).addComponent(btndrAt)))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
						.addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(btninsertar).addComponent(btneliminar).addComponent(btnmodificar)
								.addComponent(btnactualizar))
						.addGap(20, 20, 20)));

		jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 216, 751, -1));

		jPanel1.add(jPanel2, "card2");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
				javax.swing.GroupLayout.PREFERRED_SIZE));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
				javax.swing.GroupLayout.PREFERRED_SIZE));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void tablacasoestudioMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_tablacasoestudioMouseClicked
		// TODO add your handling code here:
		muestraExperimentacion();
		btneliminar.setEnabled(true);
		btnmodificar.setEnabled(true);
		btninsertar.setEnabled(false);
	}// GEN-LAST:event_tablacasoestudioMouseClicked

	private void lblimagenMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_lblimagenMouseClicked
		// TODO add your handling code here:
		fc = new JFileChooser();
		int opc = fc.showOpenDialog(this);
		if (opc == JFileChooser.APPROVE_OPTION) {
			file = fc.getSelectedFile();
			System.out.println("file es distinto de null");
			foto = getToolkit().getImage(file.getAbsolutePath());
			foto = foto.getScaledInstance(lblimagen.getWidth(), lblimagen.getHeight(), Image.SCALE_DEFAULT);
			lblimagen.setIcon(new ImageIcon(foto));
		}
	}// GEN-LAST:event_lblimagenMouseClicked

	private void btnposicAActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnposicAActionPerformed
		// TODO add your handling code here:
		int indice = jlistposicion1.getSelectedIndex();
		if (!auxapasar1.contains(jlistposicion1.getSelectedValue())) {
			auxapasar1.addElement(jlistposicion1.getSelectedValue());
			// jlistposicion1.remove(jlistposicion1.getSelectedIndex());
			jlistposiciones2.setModel(auxapasar1);
		} else {
			JOptionPane.showMessageDialog(null, "La lista de destino ya contiene ese elemento");
		}
		jlistposicion1.clearSelection();
		btnposicA.setEnabled(false);
	}// GEN-LAST:event_btnposicAActionPerformed

	private void btnposicAtActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnposicAtActionPerformed
		// TODO add your handling code here:
		if (auxapasar1 != null) {
			auxapasar1.remove(jlistposiciones2.getSelectedIndex());
		}
		btndrAt.setEnabled(false);
	}// GEN-LAST:event_btnposicAtActionPerformed

	private void btndrAActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btndrAActionPerformed
		// TODO add your handling code here:
		if (!auxapasar2.contains(jlistdimr1.getSelectedValue())) {
			auxapasar2.addElement(jlistdimr1.getSelectedValue());
			// jlistposicion1.remove(jlistposicion1.getSelectedIndex());
			jlistdimr2.setModel(auxapasar2);
		} else {
			JOptionPane.showMessageDialog(null, "La lista de destino ya contiene ese elemento");
		}
		jlistdimr1.clearSelection();
		btndrA.setEnabled(false);
	}// GEN-LAST:event_btndrAActionPerformed

	private void btndrAtActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btndrAtActionPerformed
		// TODO add your handling code here:
		if (auxapasar2 != null) {
			auxapasar2.remove(jlistdimr2.getSelectedIndex());
		}
		btndrAt.setEnabled(false);
	}// GEN-LAST:event_btndrAtActionPerformed

	private void btninsertarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btninsertarActionPerformed
		// TODO add your handling code here:
		if (!validaDatos()) {
			List<Posicionespuestotrabajo> ppt = llenarListadePosicines();
			List<DimensionesRelevantes> dr = llenarListaDimensionesR();
			Experimentacion completa = new Experimentacion();
			completa.setNombre(txtnombre.getText());
			completa.setDescripcion(txtAdescripcion.getText());
			completa.setDimensionesRelevantesList(dr);
			completa.setPosicionespuestotrabajoList(ppt);
			if (file != null) {
				try {
					is = new FileInputStream(file);
					imgbyte = new byte[(int) file.length()];
					int lector = is.read(imgbyte);
					completa.setPuestotrabaj(imgbyte);
				} catch (IOException ex) {
					Logger.getLogger(casoestudio.class.getName()).log(Level.SEVERE, null, ex);
				}
			}
			controlexp.create(completa);
			clearComponentes();
		}

		modeltabla.setRowCount(0);
		llenaTablaExperimentacio();
		file = null;
		modeloexp = null;

	}// GEN-LAST:event_btninsertarActionPerformed

	private void btnactualizarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnactualizarActionPerformed
		// TODO add your handling code here:
		/*
		 * List<Posicionespuestotrabajo> aux4=llenarListadePosicines(); for
		 * (Posicionespuestotrabajo posicionespuestotrabajo : aux4) {
		 * System.out.println("Estas son las dimensiones que contiene la lista: "
		 * +posicionespuestotrabajo.getIdposicionespuesto()); }
		 */
		modeltabla.setRowCount(0);
		file = null;
		modeloexp = null;
		llenaTablaExperimentacio();
		clearComponentes();
		btneliminar.setEnabled(false);
		btnmodificar.setEnabled(false);
		btninsertar.setEnabled(true);
	}// GEN-LAST:event_btnactualizarActionPerformed

	private void btneliminarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btneliminarActionPerformed
		try {
			// TODO add your handling code here:
			controlexp.destroy(getExperimentacion().getIdExperimentacion());

		} catch (IllegalOrphanException ex) {
			Logger.getLogger(casoestudio.class.getName()).log(Level.SEVERE, null, ex);
		} catch (NonexistentEntityException ex) {
			Logger.getLogger(casoestudio.class.getName()).log(Level.SEVERE, null, ex);
		}
		modeltabla.setRowCount(0);
		llenaTablaExperimentacio();
		file = null;
		modeloexp = null;
		clearComponentes();
		btneliminar.setEnabled(false);
		btnmodificar.setEnabled(false);
		btninsertar.setEnabled(true);
	}// GEN-LAST:event_btneliminarActionPerformed

	private void btnmodificarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnmodificarActionPerformed
		// TODO add your handling code here:
		if (modeloexp != null) {
			List<DimensionesRelevantes> dr = llenarListaDimensionesR();
			modeloexp.setNombre(txtnombre.getText());
			modeloexp.setDescripcion(txtAdescripcion.getText());
			modeloexp.setDimensionesRelevantesList(dr);
			if (file != null) {
				try {
					is = new FileInputStream(file);
					imgbyte = new byte[(int) file.length()];
					int lector = is.read(imgbyte);
					modeloexp.setPuestotrabaj(imgbyte);
					System.out.println("cambie la imagen");
				} catch (IOException ex) {
					Logger.getLogger(casoestudio.class.getName()).log(Level.SEVERE, null, ex);
				}
			}
			try {
				controlexp.edit(modeloexp);
			} catch (NonexistentEntityException ex) {
				Logger.getLogger(casoestudio.class.getName()).log(Level.SEVERE, null, ex);
			} catch (Exception ex) {
				Logger.getLogger(casoestudio.class.getName()).log(Level.SEVERE, null, ex);
			}
		} else {
			JOptionPane.showMessageDialog(null, "El caso de estudio no se encuentra en la bd");
		}

		modeltabla.setRowCount(0);
		llenaTablaExperimentacio();
		modeloexp = null;
		file = null;
		clearComponentes();
		btneliminar.setEnabled(false);
		btnmodificar.setEnabled(false);
		btninsertar.setEnabled(true);
	}// GEN-LAST:event_btnmodificarActionPerformed

	private void jlistposicion1MouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jlistposicion1MouseClicked
		// TODO add your handling code here:
		btnposicA.setEnabled(true);
	}// GEN-LAST:event_jlistposicion1MouseClicked

	private void jlistposiciones2MouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jlistposiciones2MouseClicked
		// TODO add your handling code here:
		btndrAt.setEnabled(true);
	}// GEN-LAST:event_jlistposiciones2MouseClicked

	private void jlistdimr1MouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jlistdimr1MouseClicked
		// TODO add your handling code here:
		// btnposicA.setEnabled(true);

	}// GEN-LAST:event_jlistdimr1MouseClicked

	private void jlistdimr2MouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jlistdimr2MouseClicked
		// TODO add your handling code here:
		// btndrAt.setEnabled(false);
	}// GEN-LAST:event_jlistdimr2MouseClicked

	private void jlistposicion1ValueChanged(javax.swing.event.ListSelectionEvent evt) {// GEN-FIRST:event_jlistposicion1ValueChanged
		// TODO add your handling code here:
		btnposicA.setEnabled(true);
	}// GEN-LAST:event_jlistposicion1ValueChanged

	private void jlistposiciones2ValueChanged(javax.swing.event.ListSelectionEvent evt) {// GEN-FIRST:event_jlistposiciones2ValueChanged
		// TODO add your handling code here:
		btnposicAt.setEnabled(true);
	}// GEN-LAST:event_jlistposiciones2ValueChanged

	private void jlistdimr1ValueChanged(javax.swing.event.ListSelectionEvent evt) {// GEN-FIRST:event_jlistdimr1ValueChanged
		// TODO add your handling code here:
		btndrA.setEnabled(true);
	}// GEN-LAST:event_jlistdimr1ValueChanged

	private void jlistdimr2ValueChanged(javax.swing.event.ListSelectionEvent evt) {// GEN-FIRST:event_jlistdimr2ValueChanged
		// TODO add your handling code here:
		btndrAt.setEnabled(true);
	}// GEN-LAST:event_jlistdimr2ValueChanged

	/**
	 * @param args the command line arguments
	 */
	// **************************************************FUNCIONES
	private List<Posicionespuestotrabajo> llenarListadePosicines() {
		List<Posicionespuestotrabajo> puestos1 = new LinkedList<Posicionespuestotrabajo>();
		Posicionespuestotrabajo puestoaux;
		for (int i = 0; i < auxapasar1.getSize(); i++) {
			String nombre = (String) auxapasar1.getElementAt(i);
			// puestoaux=new Posicionespuestotrabajo();
			// puestoaux.setDescripcion(nombre);
			puestos1.add(controlposicPT.findByName(nombre));
			System.out.println("esto es lo que contiene " + nombre);
		}
		return puestos1;
	}

	private List<DimensionesRelevantes> llenarListaDimensionesR() {
		List<DimensionesRelevantes> puestos1 = new LinkedList<DimensionesRelevantes>();
		for (int i = 0; i < auxapasar2.getSize(); i++) {
			String nombre = (String) auxapasar2.getElementAt(i);
			// puestoaux=new Posicionespuestotrabajo();
			// puestoaux.setDescripcion(nombre);
			puestos1.add(controldimr.findByName(nombre));
			System.out.println("esto es lo que contiene " + nombre);
		}
		return puestos1;
	}

	private void llenaTablaExperimentacio() {
		modeltabla = (DefaultTableModel) tablacasoestudio.getModel();
		List<Experimentacion> lista = controlexp.findExperimentacionEntities();
		for (Experimentacion exper : lista) {
			modeltabla.addRow(new Object[] { exper.getNombre(), exper.getDescripcion() });
		}
		tablacasoestudio.setModel(modeltabla);

	}

	private void muestraExperimentacion() {
		modeloexp = getExperimentacion();
		if (modeloexp != null) {
			txtnombre.setText(modeloexp.getNombre());
			txtAdescripcion.setText(modeloexp.getDescripcion());
			llenalistPosc(jlistposiciones2);
			llenalistDimR(jlistdimr2);
			// jlistdimr1.setEnabled(false);
			jlistposicion1.setEnabled(false);
			if (modeloexp.getPuestotrabaj() != null) {
				foto = new ToolkitImage(new ByteArrayImageSource(modeloexp.getPuestotrabaj()));
				foto = foto.getScaledInstance(lblimagen.getWidth(), lblimagen.getHeight(), Image.SCALE_DEFAULT);
				lblimagen.setIcon(new ImageIcon(foto));
			}
		}
	}

	private void clearComponentes() {
		txtnombre.setText("");
		txtAdescripcion.setText("");
		auxapasar1.removeAllElements();
		auxapasar2.removeAllElements();
		lblimagen.setIcon(null);
		modellist1.removeAllElements();
		modellist2.removeAllElements();
		jlistdimr2.removeAll();
		jlistposiciones2.removeAll();
	}

	private Experimentacion getExperimentacion() {
		Experimentacion result = null;
		int aux = tablacasoestudio.getSelectedRow();
		result = controlexp.findExperimentacionEntities().get(aux);
		return result;
	}

	private void llenalistPosc(JList list) {
		modellist1 = new DefaultListModel();
		List<Posicionespuestotrabajo> lista = modeloexp.getPosicionespuestotrabajoList();
		for (Posicionespuestotrabajo posicionespuestotrabajo : lista) {
			modellist1.addElement(posicionespuestotrabajo.getDescripcion());
		}
		list.setModel(modellist1);
		// modellist1=null;
	}

	private void llenalistDimR(JList list) {
		modellist2 = new DefaultListModel();
		List<DimensionesRelevantes> lista = modeloexp.getDimensionesRelevantesList();
		for (DimensionesRelevantes dimensionesRelevantes : lista) {
			modellist2.addElement(dimensionesRelevantes.getNombDimension());
		}
		list.setModel(modellist2);
		// modellist2=null;
	}

	private void llenaListaDR() {
		modellist1 = new DefaultListModel();
		List<DimensionesRelevantes> listdr = controldimr.findDimensionesRelevantesEntities();
		for (DimensionesRelevantes dimensionesRelevantes : listdr) {
			modellist1.addElement(dimensionesRelevantes.getNombDimension());
		}
		jlistdimr1.setModel(modellist1);
		modellist1 = null;
	}

	private void llenaListaPP() {
		modellist2 = new DefaultListModel();
		List<Posicionespuestotrabajo> listdr = controlposicPT.findPosicionespuestotrabajoEntities();
		for (Posicionespuestotrabajo posicionespuestotrabajo : listdr) {
			modellist2.addElement(posicionespuestotrabajo.getDescripcion());
		}
		jlistposicion1.setModel(modellist2);
		modellist2 = null;
	}

	private boolean validaDatos() {
		boolean valor = false;
		if (txtAdescripcion.getText().isEmpty()) {
			valor = true;
			JOptionPane.showMessageDialog(null, "Usted debe completar los datos que se le piden");
		} else if (txtnombre.getText().isEmpty()) {
			valor = true;
			JOptionPane.showMessageDialog(null, "Usted debe completar los datos que se le piden");
		} else if (jlistposiciones2.getModel().getSize() == 0) {
			valor = true;
			JOptionPane.showMessageDialog(null, "Usted debe completar los datos que se le piden");
		} else {
			if (jlistdimr2.getModel().getSize() == 0) {
				valor = true;
				JOptionPane.showMessageDialog(null, "Usted debe completar los datos que se le piden");
			}
		}
		return valor;
	}

	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		/*
		 * try { for (javax.swing.UIManager.LookAndFeelInfo info :
		 * javax.swing.UIManager.getInstalledLookAndFeels()) { if
		 * ("Nimbus".equals(info.getName())) {
		 * javax.swing.UIManager.setLookAndFeel(info.getClassName()); break; } } } catch
		 * (ClassNotFoundException ex) {
		 * java.util.logging.Logger.getLogger(casoestudio.class.getName()).log(java.util
		 * .logging.Level.SEVERE, null, ex); } catch (InstantiationException ex) {
		 * java.util.logging.Logger.getLogger(casoestudio.class.getName()).log(java.util
		 * .logging.Level.SEVERE, null, ex); } catch (IllegalAccessException ex) {
		 * java.util.logging.Logger.getLogger(casoestudio.class.getName()).log(java.util
		 * .logging.Level.SEVERE, null, ex); } catch
		 * (javax.swing.UnsupportedLookAndFeelException ex) {
		 * java.util.logging.Logger.getLogger(casoestudio.class.getName()).log(java.util
		 * .logging.Level.SEVERE, null, ex); }
		 */
		// </editor-fold>

		/* Create and display the dialog */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				casoestudio dialog = new casoestudio(new javax.swing.JFrame(), true);
				dialog.addWindowListener(new java.awt.event.WindowAdapter() {
					@Override
					public void windowClosing(java.awt.event.WindowEvent e) {
						System.exit(0);
					}
				});
				dialog.setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton btnactualizar;
	private javax.swing.JButton btndrA;
	private javax.swing.JButton btndrAt;
	private javax.swing.JButton btneliminar;
	private javax.swing.JButton btninsertar;
	private javax.swing.JButton btnmodificar;
	private javax.swing.JButton btnposicA;
	private javax.swing.JButton btnposicAt;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JLabel jLabel9;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JPanel jPanel4;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JScrollPane jScrollPane2;
	private javax.swing.JScrollPane jScrollPane3;
	private javax.swing.JScrollPane jScrollPane4;
	private javax.swing.JScrollPane jScrollPane5;
	private javax.swing.JScrollPane jScrollPane6;
	private javax.swing.JScrollPane jScrollPane7;
	private javax.swing.JList jlistdimr1;
	private javax.swing.JList jlistdimr2;
	private javax.swing.JList jlistposicion1;
	private javax.swing.JList jlistposiciones2;
	private javax.swing.JLabel lblimagen;
	private javax.swing.JTable tablacasoestudio;
	private javax.swing.JTextArea txtAdescripcion;
	private javax.swing.JTextField txtnombre;
	// End of variables declaration//GEN-END:variables
}
