/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Vista;

import Controlador.DimensionesJpaController;
import Modelo.Dimensiones;
import Modelo.Instrumento;
import Modelo.Posturas;
import Util.UserInterfaceSuport;
import com.mysql.jdbc.Connection;
import java.awt.Image;
import java.io.File;
import java.io.InputStream;
import java.util.List;
import javax.persistence.Query;
import javax.swing.JOptionPane;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.swing.ImageIcon;
import sun.awt.image.ByteArrayImageSource;
import sun.awt.image.ToolkitImage;




/**
 *
 * @author Eduardo
 */
public class TeoriaGeneral extends javax.swing.JDialog {

    /**
     * Creates new form vista
     */
    
    public static String seleccion="";
    private DimensionesJpaController controldimensiones;
    private Dimensiones modelodimensiones;  Dimensiones we;
    InputStream aus;
    byte[] img;
    Image foto; Image image;
    File aux; Connection con;
    
    public TeoriaGeneral() {
        initComponents();
        UserInterfaceSuport.centerComponent(this);
        this.setModal(true);
        this.controldimensiones = new DimensionesJpaController(javax.persistence.Persistence.createEntityManagerFactory("Prueba5PU"));
        cargarDimension(seleccion);
    }
    public void cargarDimension(String nombre){
        /*-EntityManagerFactory emf =  Persistence.createEntityManagerFactory("Laboratorio_VirtualPU");
        EntityManager em = emf.createEntityManager();
        Query query=em.createQuery("SELECT a FROM dimensiones a WHERE a.nombmedid='Estatura'");*/
        //query.setParameter("dnombre",nombre);
        //Dimensiones we=(Dimensiones) query.getSingleResult();
        //Dimensiones we=controldimensiones.findNombMedida(nombre);
        //******************************************************
        //funciona
        we=controldimensiones.Mostrar(nombre);
        if (we==null) {
            we=new Dimensiones();
            JOptionPane.showMessageDialog(null, "la dimension tomada no existe en la base de datos");
        }
        System.out.println("hola"+ we.getDescripMedida()+"/n"); 
        //JOptionPane.showMessageDialog(imagenpanel, we.getDescripMedida());
         //****************************************************************
        lblnombre.setText(we.getNombmedid());
        lbldescripcion.setText("Descripción:"+" "+ we.getDescripMedida());
        lbluso.setText("Criterio de uso:"+" "+ we.getCriterioDeUso());
        foto = new ToolkitImage(new ByteArrayImageSource(we.getFotodim()));
        foto=foto.getScaledInstance(lblimagen.getWidth(),lblimagen.getHeight(), Image.SCALE_DEFAULT);
        lblimagen.setIcon(new ImageIcon(foto));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contenedor = new javax.swing.JPanel();
        contenedorbotones = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        lblPosturas = new javax.swing.JLabel();
        lblInstrumentos = new javax.swing.JLabel();
        lblDimension = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        descripcionScrollPane1 = new javax.swing.JScrollPane();
        lbldescripcion = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lbluso = new javax.swing.JLabel();
        contenedorimagen = new javax.swing.JPanel();
        lblimagen = new javax.swing.JLabel();
        menupanel = new javax.swing.JPanel();
        lblejercicio = new javax.swing.JLabel();
        btnayuda = new javax.swing.JButton();
        lblnombre = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        contenedor.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        contenedorbotones.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel6.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel6.setText("      Puntos");
        jLabel6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel6MouseExited(evt);
            }
        });

        lblPosturas.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        lblPosturas.setText("      Postura");
        lblPosturas.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblPosturas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblPosturas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblPosturasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblPosturasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblPosturasMouseExited(evt);
            }
        });

        lblInstrumentos.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        lblInstrumentos.setText(" Instrumento");
        lblInstrumentos.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblInstrumentos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblInstrumentos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblInstrumentosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblInstrumentosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblInstrumentosMouseExited(evt);
            }
        });

        lblDimension.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        lblDimension.setText("  Dimensión");
        lblDimension.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblDimension.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDimensionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblDimensionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblDimensionMouseExited(evt);
            }
        });

        javax.swing.GroupLayout contenedorbotonesLayout = new javax.swing.GroupLayout(contenedorbotones);
        contenedorbotones.setLayout(contenedorbotonesLayout);
        contenedorbotonesLayout.setHorizontalGroup(
            contenedorbotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblDimension, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblPosturas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblInstrumentos, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
        );
        contenedorbotonesLayout.setVerticalGroup(
            contenedorbotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenedorbotonesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblDimension, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPosturas, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblInstrumentos, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(375, Short.MAX_VALUE))
        );

        contenedor.add(contenedorbotones, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 630));

        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        descripcionScrollPane1.setBorder(null);

        lbldescripcion.setText("descripcion");
        lbldescripcion.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        descripcionScrollPane1.setViewportView(lbldescripcion);

        jPanel1.add(descripcionScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 510, 670, 50));

        jScrollPane1.setBorder(null);

        lbluso.setText("uso");
        lbluso.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jScrollPane1.setViewportView(lbluso);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 570, 670, 50));

        contenedorimagen.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createTitledBorder("Imagen"), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED)));

        lblimagen.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        javax.swing.GroupLayout contenedorimagenLayout = new javax.swing.GroupLayout(contenedorimagen);
        contenedorimagen.setLayout(contenedorimagenLayout);
        contenedorimagenLayout.setHorizontalGroup(
            contenedorimagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenedorimagenLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblimagen, javax.swing.GroupLayout.PREFERRED_SIZE, 634, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        contenedorimagenLayout.setVerticalGroup(
            contenedorimagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contenedorimagenLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblimagen, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.add(contenedorimagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 670, 490));

        contenedor.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, 690, 630));

        menupanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        menupanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblejercicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ejercitacion.jpg"))); // NOI18N
        lblejercicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblejercicioMouseClicked(evt);
            }
        });
        menupanel.add(lblejercicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 0, 50, 40));

        btnayuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ayuda.jpg"))); // NOI18N
        menupanel.add(btnayuda, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 0, 50, 40));

        lblnombre.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        menupanel.add(lblnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 0, 280, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(menupanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(menupanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contenedor, javax.swing.GroupLayout.PREFERRED_SIZE, 631, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblejercicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblejercicioMouseClicked
        // TODO add your handling code here:
        dispose();
        MostrarEjercicio dialog = new MostrarEjercicio();
        dialog.setVisible(true);
        
    }//GEN-LAST:event_lblejercicioMouseClicked

    private void lblInstrumentosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblInstrumentosMouseEntered
        // TODO add your handling code here:
        lblInstrumentos.setFont(new java.awt.Font("Tahoma", 3, 20));
    }//GEN-LAST:event_lblInstrumentosMouseEntered

    private void lblPosturasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPosturasMouseEntered
        // TODO add your handling code here:
        lblPosturas.setFont(new java.awt.Font("Tahoma", 3, 20));
    }//GEN-LAST:event_lblPosturasMouseEntered

    private void jLabel6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseEntered
        // TODO add your handling code here:
        jLabel6.setFont(new java.awt.Font("Tahoma", 3, 20));
        /*lblteo.setBorder(null);funciona para ponerlo en su posicion*/
    }//GEN-LAST:event_jLabel6MouseEntered

    private void jLabel6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseExited
        // TODO add your handling code here:
        jLabel6.setFont(new java.awt.Font("Tahoma", 3, 18));
    }//GEN-LAST:event_jLabel6MouseExited

    private void lblPosturasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPosturasMouseExited
        // TODO add your handling code here:
        lblPosturas.setFont(new java.awt.Font("Tahoma", 3, 18));
    }//GEN-LAST:event_lblPosturasMouseExited

    private void lblInstrumentosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblInstrumentosMouseExited
        // TODO add your handling code here:
        lblInstrumentos.setFont(new java.awt.Font("Tahoma", 3, 18));
    }//GEN-LAST:event_lblInstrumentosMouseExited

    private void lblInstrumentosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblInstrumentosMouseClicked
        // TODO add your handling code here:
        Instrumento instrumento=we.getIdinstrumento();
        lblnombre.setText("");
        lbldescripcion.setText("Nombre:"+" "+ instrumento.getNombInstrumento());
        lbluso.setText("Descripción:"+" "+ instrumento.getDescripInstrumento());
        foto = new ToolkitImage(new ByteArrayImageSource(instrumento.getFotoInstrumento()));
        foto=foto.getScaledInstance(lblimagen.getWidth(),lblimagen.getHeight(), Image.SCALE_DEFAULT);
        lblimagen.setIcon(new ImageIcon(foto));
    }//GEN-LAST:event_lblInstrumentosMouseClicked

    private void lblPosturasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPosturasMouseClicked
        // TODO add your handling code here:
        Posturas postura=we.getPosturasIdposturas();
        lblnombre.setText("");
        lbldescripcion.setText("Nombre:"+" "+ postura.getNombPostura());
        lbluso.setText("Descripción:"+" "+ postura.getDescripPostura());
        foto = new ToolkitImage(new ByteArrayImageSource(postura.getFotoPostura()));
        foto=foto.getScaledInstance(lblimagen.getWidth(),lblimagen.getHeight(), Image.SCALE_DEFAULT);
        lblimagen.setIcon(new ImageIcon(foto));
    }//GEN-LAST:event_lblPosturasMouseClicked

    private void lblDimensionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDimensionMouseEntered
        // TODO add your handling code here:
        lblDimension.setFont(new java.awt.Font("Tahoma", 3, 20));
    }//GEN-LAST:event_lblDimensionMouseEntered

    private void lblDimensionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDimensionMouseExited
        // TODO add your handling code here:
        lblDimension.setFont(new java.awt.Font("Tahoma", 3, 18));
    }//GEN-LAST:event_lblDimensionMouseExited

    private void lblDimensionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDimensionMouseClicked
        // TODO add your handling code here:
        lblnombre.setText(seleccion);
        lbldescripcion.setText("Nombre:"+" "+ we.getNombmedid());
        lbluso.setText("Descripción:"+" "+ we.getDescripMedida());
        foto = new ToolkitImage(new ByteArrayImageSource(we.getFotodim()));
        foto=foto.getScaledInstance(lblimagen.getWidth(),lblimagen.getHeight(), Image.SCALE_DEFAULT);
        lblimagen.setIcon(new ImageIcon(foto));
    }//GEN-LAST:event_lblDimensionMouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jLabel6MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TeoriaGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TeoriaGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TeoriaGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TeoriaGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TeoriaGeneral().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnayuda;
    private javax.swing.JPanel contenedor;
    private javax.swing.JPanel contenedorbotones;
    private javax.swing.JPanel contenedorimagen;
    private javax.swing.JScrollPane descripcionScrollPane1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDimension;
    private javax.swing.JLabel lblInstrumentos;
    private javax.swing.JLabel lblPosturas;
    private javax.swing.JLabel lbldescripcion;
    private javax.swing.JLabel lblejercicio;
    private javax.swing.JLabel lblimagen;
    private javax.swing.JLabel lblnombre;
    private javax.swing.JLabel lbluso;
    private javax.swing.JPanel menupanel;
    // End of variables declaration//GEN-END:variables
}
